// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(takt_coreFFI)
import takt_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_takt_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_takt_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTaktCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * An open workspace database.
 */
public protocol CoreWorkspaceProtocol: AnyObject, Sendable {
    
    /**
     * Creates a condition as one "New Condition" step; returns its id.
     */
    func createCondition(workspaceId: String, name: String, isLocation: Bool, nowMs: Int64) throws  -> String
    
    /**
     * Creates a folder as one "New Folder" step.
     */
    func createFolder(workspaceId: String, name: String, parentFolderId: String?, nowMs: Int64) throws  -> CreatedItem
    
    /**
     * Creates a list as one "New List" step.
     */
    func createList(workspaceId: String, name: String, folderId: String?, nowMs: Int64) throws  -> CreatedItem
    
    /**
     * Creates a task as one "New Task" step and returns its id.
     */
    func createTask(task: NewTask, nowMs: Int64) throws  -> String
    
    /**
     * Deletes a folder as one "Delete Folder" step; its lists move to the top.
     */
    func deleteFolder(id: String) throws 
    
    /**
     * Deletes a list and its tasks as one "Delete List" step.
     */
    func deleteList(id: String) throws  -> DeletedList
    
    /**
     * Deletes a task and its subtree as one "Delete Task" step.
     */
    func deleteTask(id: String) throws  -> DeletedTask
    
    /**
     * The task and list the next undo (`for_undo`) or redo affects.
     */
    func historyTarget(forUndo: Bool) throws  -> HistoryTarget
    
    /**
     * Indents a task under the sibling above as one "Indent Task" step.
     */
    func indentTask(id: String, nowMs: Int64) throws 
    
    /**
     * Moves a folder into another (or to the top) as one "Move Folder" step.
     */
    func moveFolder(id: String, parentFolderId: String?, nowMs: Int64) throws 
    
    /**
     * Moves a folder among its siblings as one "Reorder Folder" step.
     */
    func moveFolderWithinSiblings(id: String, offset: Int32, nowMs: Int64) throws 
    
    /**
     * Moves a list into a folder (or to the top) as one "Move List" step.
     */
    func moveList(id: String, folderId: String?, nowMs: Int64) throws 
    
    /**
     * Moves a list among its siblings as one "Reorder List" step.
     */
    func moveListWithinFolder(id: String, offset: Int32, nowMs: Int64) throws 
    
    /**
     * Moves a task and its subtree as one "Move Task" step.
     */
    func moveTask(id: String, listId: String, parentTaskId: String?, toVisibleRoot: Bool, nowMs: Int64) throws 
    
    /**
     * Drops a task before a sibling, and into a board column, as one
     * "Reorder Task" step.
     */
    func moveTaskBefore(id: String, targetId: String, kanbanColumn: String?, nowMs: Int64) throws 
    
    /**
     * Moves a task to the top of its siblings as one "Reorder Task" step.
     */
    func moveTaskToStart(id: String, nowMs: Int64) throws 
    
    /**
     * Moves a task among its siblings as one "Reorder Task" step.
     */
    func moveTaskWithinSiblings(id: String, offset: Int32, nowMs: Int64) throws 
    
    /**
     * Outdents a task to follow its parent as one "Outdent Task" step.
     */
    func outdentTask(id: String, nowMs: Int64) throws 
    
    /**
     * Drops a folder before another, in a parent, as one "Reorder Folder" step.
     */
    func placeFolder(id: String, beforeId: String?, parentFolderId: String?, nowMs: Int64) throws 
    
    /**
     * Drops a list before another, in a folder, as one "Reorder List" step.
     */
    func placeList(id: String, beforeId: String?, folderId: String?, nowMs: Int64) throws 
    
    /**
     * Puts back the most recently undone step.
     */
    func redo() throws  -> String?
    
    /**
     * What redo would put back.
     */
    func redoableLabel() throws  -> String?
    
    /**
     * Renames a folder as one "Rename Folder" step.
     */
    func renameFolder(id: String, name: String, nowMs: Int64) throws 
    
    /**
     * Renames a list as one "Rename List" step.
     */
    func renameList(id: String, name: String, nowMs: Int64) throws 
    
    /**
     * Saves a condition as one "Edit Condition" step.
     */
    func saveCondition(id: String, name: String, isLocation: Bool, isArchived: Bool, nowMs: Int64) throws 
    
    /**
     * Puts tasks in a board column as one "Move Task" step.
     */
    func setKanbanColumn(taskIds: [String], column: String?, nowMs: Int64) throws 
    
    /**
     * Archives or restores a list as one "Archive List" step.
     */
    func setListArchived(id: String, archived: Bool, nowMs: Int64) throws 
    
    /**
     * Places a task on the priority matrix as one "Move Task" step.
     */
    func setMatrixPosition(id: String, urgency: Int64?, importance: Int64?, nowMs: Int64) throws 
    
    /**
     * Reverses the most recent step; returns its label, or nothing when there
     * was nothing to undo.
     */
    func undo() throws  -> String?
    
    /**
     * The journal's named steps, newest first.
     */
    func undoHistory(limit: UInt32) throws  -> [UndoStep]
    
    /**
     * What undo would take back, phrased for a menu item.
     */
    func undoableLabel() throws  -> String?
    
    /**
     * Sets a list's name and colour as one "Edit List" step.
     */
    func updateList(id: String, name: String, colourHex: String?, nowMs: Int64) throws 
    
}
/**
 * An open workspace database.
 */
open class CoreWorkspace: CoreWorkspaceProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_takt_core_fn_clone_coreworkspace(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_takt_core_fn_free_coreworkspace(handle, $0) }
    }

    
    /**
     * Opens the database at `path`, which must already be migrated
     * ([`crate::schema::migrate_workspace`]).
     */
public static func `open`(path: String)throws  -> CoreWorkspace  {
    return try  FfiConverterTypeCoreWorkspace_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_constructor_coreworkspace_open(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
    

    
    /**
     * Creates a condition as one "New Condition" step; returns its id.
     */
open func createCondition(workspaceId: String, name: String, isLocation: Bool, nowMs: Int64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_create_condition(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(workspaceId),
        FfiConverterString.lower(name),
        FfiConverterBool.lower(isLocation),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Creates a folder as one "New Folder" step.
     */
open func createFolder(workspaceId: String, name: String, parentFolderId: String?, nowMs: Int64)throws  -> CreatedItem  {
    return try  FfiConverterTypeCreatedItem_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_create_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(workspaceId),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(parentFolderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Creates a list as one "New List" step.
     */
open func createList(workspaceId: String, name: String, folderId: String?, nowMs: Int64)throws  -> CreatedItem  {
    return try  FfiConverterTypeCreatedItem_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_create_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(workspaceId),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(folderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Creates a task as one "New Task" step and returns its id.
     */
open func createTask(task: NewTask, nowMs: Int64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_create_task(
            self.uniffiCloneHandle(),
        FfiConverterTypeNewTask_lower(task),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
})
}
    
    /**
     * Deletes a folder as one "Delete Folder" step; its lists move to the top.
     */
open func deleteFolder(id: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_delete_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
}
}
    
    /**
     * Deletes a list and its tasks as one "Delete List" step.
     */
open func deleteList(id: String)throws  -> DeletedList  {
    return try  FfiConverterTypeDeletedList_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_delete_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}
    
    /**
     * Deletes a task and its subtree as one "Delete Task" step.
     */
open func deleteTask(id: String)throws  -> DeletedTask  {
    return try  FfiConverterTypeDeletedTask_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_delete_task(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),uniffiCallStatus
    )
})
}
    
    /**
     * The task and list the next undo (`for_undo`) or redo affects.
     */
open func historyTarget(forUndo: Bool)throws  -> HistoryTarget  {
    return try  FfiConverterTypeHistoryTarget_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_history_target(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(forUndo),uniffiCallStatus
    )
})
}
    
    /**
     * Indents a task under the sibling above as one "Indent Task" step.
     */
open func indentTask(id: String, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_indent_task(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a folder into another (or to the top) as one "Move Folder" step.
     */
open func moveFolder(id: String, parentFolderId: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(parentFolderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a folder among its siblings as one "Reorder Folder" step.
     */
open func moveFolderWithinSiblings(id: String, offset: Int32, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_folder_within_siblings(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt32.lower(offset),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a list into a folder (or to the top) as one "Move List" step.
     */
open func moveList(id: String, folderId: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(folderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a list among its siblings as one "Reorder List" step.
     */
open func moveListWithinFolder(id: String, offset: Int32, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_list_within_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt32.lower(offset),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a task and its subtree as one "Move Task" step.
     */
open func moveTask(id: String, listId: String, parentTaskId: String?, toVisibleRoot: Bool, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_task(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(listId),
        FfiConverterOptionString.lower(parentTaskId),
        FfiConverterBool.lower(toVisibleRoot),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Drops a task before a sibling, and into a board column, as one
     * "Reorder Task" step.
     */
open func moveTaskBefore(id: String, targetId: String, kanbanColumn: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_task_before(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(targetId),
        FfiConverterOptionString.lower(kanbanColumn),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a task to the top of its siblings as one "Reorder Task" step.
     */
open func moveTaskToStart(id: String, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_task_to_start(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Moves a task among its siblings as one "Reorder Task" step.
     */
open func moveTaskWithinSiblings(id: String, offset: Int32, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_move_task_within_siblings(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt32.lower(offset),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Outdents a task to follow its parent as one "Outdent Task" step.
     */
open func outdentTask(id: String, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_outdent_task(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Drops a folder before another, in a parent, as one "Reorder Folder" step.
     */
open func placeFolder(id: String, beforeId: String?, parentFolderId: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_place_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(beforeId),
        FfiConverterOptionString.lower(parentFolderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Drops a list before another, in a folder, as one "Reorder List" step.
     */
open func placeList(id: String, beforeId: String?, folderId: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_place_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(beforeId),
        FfiConverterOptionString.lower(folderId),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Puts back the most recently undone step.
     */
open func redo()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_redo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * What redo would put back.
     */
open func redoableLabel()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_redoable_label(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Renames a folder as one "Rename Folder" step.
     */
open func renameFolder(id: String, name: String, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_rename_folder(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Renames a list as one "Rename List" step.
     */
open func renameList(id: String, name: String, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_rename_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Saves a condition as one "Edit Condition" step.
     */
open func saveCondition(id: String, name: String, isLocation: Bool, isArchived: Bool, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_save_condition(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterBool.lower(isLocation),
        FfiConverterBool.lower(isArchived),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Puts tasks in a board column as one "Move Task" step.
     */
open func setKanbanColumn(taskIds: [String], column: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_set_kanban_column(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(taskIds),
        FfiConverterOptionString.lower(column),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Archives or restores a list as one "Archive List" step.
     */
open func setListArchived(id: String, archived: Bool, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_set_list_archived(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterBool.lower(archived),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Places a task on the priority matrix as one "Move Task" step.
     */
open func setMatrixPosition(id: String, urgency: Int64?, importance: Int64?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_set_matrix_position(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterOptionInt64.lower(urgency),
        FfiConverterOptionInt64.lower(importance),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    
    /**
     * Reverses the most recent step; returns its label, or nothing when there
     * was nothing to undo.
     */
open func undo()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_undo(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * The journal's named steps, newest first.
     */
open func undoHistory(limit: UInt32)throws  -> [UndoStep]  {
    return try  FfiConverterSequenceTypeUndoStep.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_undo_history(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(limit),uniffiCallStatus
    )
})
}
    
    /**
     * What undo would take back, phrased for a menu item.
     */
open func undoableLabel()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_undoable_label(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Sets a list's name and colour as one "Edit List" step.
     */
open func updateList(id: String, name: String, colourHex: String?, nowMs: Int64)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_method_coreworkspace_update_list(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(colourHex),
        FfiConverterInt64.lower(nowMs),uniffiCallStatus
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreWorkspace: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CoreWorkspace

    public static func lift(_ handle: UInt64) throws -> CoreWorkspace {
        return CoreWorkspace(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CoreWorkspace) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreWorkspace {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CoreWorkspace, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreWorkspace_lift(_ handle: UInt64) throws -> CoreWorkspace {
    return try FfiConverterTypeCoreWorkspace.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreWorkspace_lower(_ value: CoreWorkspace) -> UInt64 {
    return FfiConverterTypeCoreWorkspace.lower(value)
}




/**
 * A folder or list [`create_folder`] or [`create_list`] made: what a client
 * needs to build its own model of it, beside what it already passed in.
 */
public struct CreatedItem: Equatable, Hashable {
    public var id: String
    /**
     * The name as stored, trimmed.
     */
    public var name: String
    /**
     * Its place among its siblings: after the last of them.
     */
    public var sortOrder: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, 
        /**
         * The name as stored, trimmed.
         */name: String, 
        /**
         * Its place among its siblings: after the last of them.
         */sortOrder: Int64) {
        self.id = id
        self.name = name
        self.sortOrder = sortOrder
    }

    

    
}

#if compiler(>=6)
extension CreatedItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreatedItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreatedItem {
        return
            try CreatedItem(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                sortOrder: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CreatedItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt64.write(value.sortOrder, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatedItem_lift(_ buf: RustBuffer) throws -> CreatedItem {
    return try FfiConverterTypeCreatedItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreatedItem_lower(_ value: CreatedItem) -> RustBuffer {
    return FfiConverterTypeCreatedItem.lower(value)
}


/**
 * What [`delete_list`] removed.
 */
public struct DeletedList: Equatable, Hashable {
    public var id: String
    public var name: String
    /**
     * How many tasks went with it.
     */
    public var tasksDeleted: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, 
        /**
         * How many tasks went with it.
         */tasksDeleted: UInt32) {
        self.id = id
        self.name = name
        self.tasksDeleted = tasksDeleted
    }

    

    
}

#if compiler(>=6)
extension DeletedList: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeletedList: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeletedList {
        return
            try DeletedList(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                tasksDeleted: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: DeletedList, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.tasksDeleted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeletedList_lift(_ buf: RustBuffer) throws -> DeletedList {
    return try FfiConverterTypeDeletedList.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeletedList_lower(_ value: DeletedList) -> RustBuffer {
    return FfiConverterTypeDeletedList.lower(value)
}


/**
 * What [`delete_task`] removed.
 */
public struct DeletedTask: Equatable, Hashable {
    public var id: String
    public var title: String
    /**
     * How many tasks below it went with it.
     */
    public var subtasksDeleted: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, 
        /**
         * How many tasks below it went with it.
         */subtasksDeleted: UInt32) {
        self.id = id
        self.title = title
        self.subtasksDeleted = subtasksDeleted
    }

    

    
}

#if compiler(>=6)
extension DeletedTask: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeletedTask: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeletedTask {
        return
            try DeletedTask(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                subtasksDeleted: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: DeletedTask, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterUInt32.write(value.subtasksDeleted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeletedTask_lift(_ buf: RustBuffer) throws -> DeletedTask {
    return try FfiConverterTypeDeletedTask.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeletedTask_lower(_ value: DeletedTask) -> RustBuffer {
    return FfiConverterTypeDeletedTask.lower(value)
}


/**
 * The task and list the next undo (or redo) affects, so a client can reveal
 * the work that comes back.
 */
public struct HistoryTarget: Equatable, Hashable {
    public var taskId: String?
    public var listId: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(taskId: String?, listId: String?) {
        self.taskId = taskId
        self.listId = listId
    }

    

    
}

#if compiler(>=6)
extension HistoryTarget: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHistoryTarget: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HistoryTarget {
        return
            try HistoryTarget(
                taskId: FfiConverterOptionString.read(from: &buf), 
                listId: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HistoryTarget, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.taskId, into: &buf)
        FfiConverterOptionString.write(value.listId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryTarget_lift(_ buf: RustBuffer) throws -> HistoryTarget {
    return try FfiConverterTypeHistoryTarget.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryTarget_lower(_ value: HistoryTarget) -> RustBuffer {
    return FfiConverterTypeHistoryTarget.lower(value)
}


/**
 * A task to create: everything any client can set when it adds one.
 */
public struct NewTask: Equatable, Hashable {
    public var listId: String
    public var title: String
    public var parentTaskId: String?
    /**
     * `"task"`, or `"list"` for a nested list.
     */
    public var kind: String
    public var notes: String
    public var kanbanColumn: String?
    public var startAtMs: Int64?
    public var dueAtMs: Int64?
    public var estimateSeconds: Int64?
    public var tags: [String]
    /**
     * 1 to 4; anything else is no priority.
     */
    public var priority: Int64?
    /**
     * Who it waits on; puts it in the waiting column.
     */
    public var waitingOn: String?
    public var externalLinks: [String]
    /**
     * First among its siblings rather than last.
     */
    public var atTop: Bool
    /**
     * A sibling to go beside: below it, or above with `above`.
     */
    public var adjacentTaskId: String?
    public var above: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(listId: String, title: String, parentTaskId: String?, 
        /**
         * `"task"`, or `"list"` for a nested list.
         */kind: String, notes: String, kanbanColumn: String?, startAtMs: Int64?, dueAtMs: Int64?, estimateSeconds: Int64?, tags: [String], 
        /**
         * 1 to 4; anything else is no priority.
         */priority: Int64?, 
        /**
         * Who it waits on; puts it in the waiting column.
         */waitingOn: String?, externalLinks: [String], 
        /**
         * First among its siblings rather than last.
         */atTop: Bool, 
        /**
         * A sibling to go beside: below it, or above with `above`.
         */adjacentTaskId: String?, above: Bool) {
        self.listId = listId
        self.title = title
        self.parentTaskId = parentTaskId
        self.kind = kind
        self.notes = notes
        self.kanbanColumn = kanbanColumn
        self.startAtMs = startAtMs
        self.dueAtMs = dueAtMs
        self.estimateSeconds = estimateSeconds
        self.tags = tags
        self.priority = priority
        self.waitingOn = waitingOn
        self.externalLinks = externalLinks
        self.atTop = atTop
        self.adjacentTaskId = adjacentTaskId
        self.above = above
    }

    

    
}

#if compiler(>=6)
extension NewTask: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNewTask: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NewTask {
        return
            try NewTask(
                listId: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                parentTaskId: FfiConverterOptionString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                kanbanColumn: FfiConverterOptionString.read(from: &buf), 
                startAtMs: FfiConverterOptionInt64.read(from: &buf), 
                dueAtMs: FfiConverterOptionInt64.read(from: &buf), 
                estimateSeconds: FfiConverterOptionInt64.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                priority: FfiConverterOptionInt64.read(from: &buf), 
                waitingOn: FfiConverterOptionString.read(from: &buf), 
                externalLinks: FfiConverterSequenceString.read(from: &buf), 
                atTop: FfiConverterBool.read(from: &buf), 
                adjacentTaskId: FfiConverterOptionString.read(from: &buf), 
                above: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: NewTask, into buf: inout [UInt8]) {
        FfiConverterString.write(value.listId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.parentTaskId, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterOptionString.write(value.kanbanColumn, into: &buf)
        FfiConverterOptionInt64.write(value.startAtMs, into: &buf)
        FfiConverterOptionInt64.write(value.dueAtMs, into: &buf)
        FfiConverterOptionInt64.write(value.estimateSeconds, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionInt64.write(value.priority, into: &buf)
        FfiConverterOptionString.write(value.waitingOn, into: &buf)
        FfiConverterSequenceString.write(value.externalLinks, into: &buf)
        FfiConverterBool.write(value.atTop, into: &buf)
        FfiConverterOptionString.write(value.adjacentTaskId, into: &buf)
        FfiConverterBool.write(value.above, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNewTask_lift(_ buf: RustBuffer) throws -> NewTask {
    return try FfiConverterTypeNewTask.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNewTask_lower(_ value: NewTask) -> RustBuffer {
    return FfiConverterTypeNewTask.lower(value)
}


/**
 * One named step in the journal, as [`history`] reports it.
 */
public struct UndoStep: Equatable, Hashable {
    /**
     * The journal group the step's changes share.
     */
    public var id: String
    /**
     * What the step is offered back as: "New Task", "Delete List".
     */
    public var label: String
    /**
     * Undone steps are the redo stack.
     */
    public var isUndone: Bool
    /**
     * How many rows the step touched.
     */
    public var changeCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The journal group the step's changes share.
         */id: String, 
        /**
         * What the step is offered back as: "New Task", "Delete List".
         */label: String, 
        /**
         * Undone steps are the redo stack.
         */isUndone: Bool, 
        /**
         * How many rows the step touched.
         */changeCount: UInt32) {
        self.id = id
        self.label = label
        self.isUndone = isUndone
        self.changeCount = changeCount
    }

    

    
}

#if compiler(>=6)
extension UndoStep: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUndoStep: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UndoStep {
        return
            try UndoStep(
                id: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                isUndone: FfiConverterBool.read(from: &buf), 
                changeCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: UndoStep, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterBool.write(value.isUndone, into: &buf)
        FfiConverterUInt32.write(value.changeCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoStep_lift(_ buf: RustBuffer) throws -> UndoStep {
    return try FfiConverterTypeUndoStep.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUndoStep_lower(_ value: UndoStep) -> RustBuffer {
    return FfiConverterTypeUndoStep.lower(value)
}


/**
 * What went wrong in the core, as a client sees it.
 *
 * The field is `detail` rather than `message`: Kotlin's generated exception
 * would otherwise clash with `Throwable.message`.
 */
public 
enum CoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Database(detail: String
    )
    case ForeignKeys(identifier: String, count: UInt32
    )
    case NoJournal
    case MissingTask(id: String
    )
    case MissingList(id: String
    )
    case MissingFolder(id: String
    )
    case SystemListIsPermanent
    case EmptyName
    case InvalidFolderMove
    case InvalidCondition
    case InvalidTaskMove

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Database(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ForeignKeys(
            identifier: try FfiConverterString.read(from: &buf), 
            count: try FfiConverterUInt32.read(from: &buf)
            )
        case 3: return .NoJournal
        case 4: return .MissingTask(
            id: try FfiConverterString.read(from: &buf)
            )
        case 5: return .MissingList(
            id: try FfiConverterString.read(from: &buf)
            )
        case 6: return .MissingFolder(
            id: try FfiConverterString.read(from: &buf)
            )
        case 7: return .SystemListIsPermanent
        case 8: return .EmptyName
        case 9: return .InvalidFolderMove
        case 10: return .InvalidCondition
        case 11: return .InvalidTaskMove

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Database(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .ForeignKeys(identifier,count):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(identifier, into: &buf)
            FfiConverterUInt32.write(count, into: &buf)
            
        
        case .NoJournal:
            writeInt(&buf, Int32(3))
        
        
        case let .MissingTask(id):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .MissingList(id):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .MissingFolder(id):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(id, into: &buf)
            
        
        case .SystemListIsPermanent:
            writeInt(&buf, Int32(7))
        
        
        case .EmptyName:
            writeInt(&buf, Int32(8))
        
        
        case .InvalidFolderMove:
            writeInt(&buf, Int32(9))
        
        
        case .InvalidCondition:
            writeInt(&buf, Int32(10))
        
        
        case .InvalidTaskMove:
            writeInt(&buf, Int32(11))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUndoStep: FfiConverterRustBuffer {
    typealias SwiftType = [UndoStep]

    public static func write(_ value: [UndoStep], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUndoStep.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UndoStep] {
        let len: Int32 = try readInt(&buf)
        var seq = [UndoStep]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUndoStep.read(from: &buf))
        }
        return seq
    }
}
/**
 * The version of this crate, as compiled into the library a client loaded.
 *
 * The first call across the boundary, and the one a client shows in its
 * diagnostics: when a platform's bindings and its compiled library drift
 * apart, this is the number that says which library it actually has.
 */
public func coreVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_takt_core_fn_func_core_version(uniffiCallStatus
    )
})
}
/**
 * Brings the database at `path` up to date, creating it if it does not
 * exist, and returns the identifier of the newest migration it now has.
 *
 * Opens its own connection and closes it before returning, so call it
 * before the client opens the file. Waits up to five seconds for another
 * writer, as every client does.
 */
public func migrateWorkspace(path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_takt_core_fn_func_migrate_workspace(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
/**
 * The migration identifiers, oldest first.
 */
public func workspaceMigrations() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_takt_core_fn_func_workspace_migrations(uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_takt_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_takt_core_checksum_func_core_version() != 3784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_func_migrate_workspace() != 222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_func_workspace_migrations() != 25592) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_create_condition() != 36493) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_create_folder() != 9864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_create_list() != 11553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_create_task() != 36329) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_delete_folder() != 27954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_delete_list() != 34244) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_delete_task() != 40901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_history_target() != 25210) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_indent_task() != 14168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_folder() != 35092) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_folder_within_siblings() != 18801) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_list() != 22532) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_list_within_folder() != 53589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_task() != 61445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_task_before() != 26716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_task_to_start() != 39003) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_move_task_within_siblings() != 3701) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_outdent_task() != 3744) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_place_folder() != 1445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_place_list() != 14409) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_redo() != 49682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_redoable_label() != 40840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_rename_folder() != 13587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_rename_list() != 3217) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_save_condition() != 40969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_set_kanban_column() != 29324) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_set_list_archived() != 35767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_set_matrix_position() != 2656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_undo() != 20533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_undo_history() != 28985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_undoable_label() != 37156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_method_coreworkspace_update_list() != 5208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takt_core_checksum_constructor_coreworkspace_open() != 50515) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTaktCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all