#!/usr/bin/env bash
# Snapshot the workspace database's schema — DDL only, never a row of data —
# into the fixture the CLI's workspace-write tests build their databases from.
#
# The tests need the app's real tables, and in particular its real triggers:
# the `change_log` triggers that make a write undoable and the FTS5 triggers
# that keep search level with the tasks table. A hand-written schema would test
# the CLI against what someone remembered the app doing.
#
# Run after adding a migration to WorkspaceStore, against a database the app
# has migrated (by default, the app's own, opened read-only):
#
#   scripts/dump_workspace_schema.sh [path/to/priority.sqlite]
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
database="${1:-$HOME/Library/Application Support/Priority/priority.sqlite}"
output="$root/cli/src/fixtures/workspace_schema.sql"

mkdir -p "$(dirname "$output")"

latest="$(sqlite3 -readonly "file:$database?mode=ro" \
  "SELECT identifier FROM grdb_migrations ORDER BY rowid DESC LIMIT 1;")"

{
  echo "-- The app's workspace schema, DDL only, as of ${latest}."
  echo "-- Generated by scripts/dump_workspace_schema.sh; do not edit by hand."
  # sqlite_sequence and the FTS5 shadow tables are created by SQLite itself,
  # and creating them by hand is an error.
  sqlite3 -readonly "file:$database?mode=ro" \
    "SELECT sql || ';' FROM sqlite_master
     WHERE sql IS NOT NULL
       AND name <> 'sqlite_sequence'
       AND name NOT LIKE 'tasks_fts_%'
     ORDER BY rowid;"
  echo
  echo "-- The migration ledger, so a fixture reads as migrated."
  sqlite3 -readonly "file:$database?mode=ro" \
    "SELECT 'INSERT INTO grdb_migrations (identifier) VALUES (''' || identifier || ''');'
     FROM grdb_migrations ORDER BY rowid;"
  echo "INSERT INTO undo_control (id, suppressed) VALUES (0, 1);"
} > "$output"

echo "Wrote $output (${latest})"
