-- The app's workspace schema, DDL only, as of v18_themes_and_preferences.
-- Generated by scripts/dump_workspace_schema.sh; do not edit by hand.
CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY);
CREATE TABLE "workspaces" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "list_folders" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "parentFolderId" TEXT REFERENCES "list_folders"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE INDEX "list_folders_on_workspaceId" ON "list_folders"("workspaceId");
CREATE INDEX "list_folders_on_parentFolderId" ON "list_folders"("parentFolderId");
CREATE TABLE "task_lists" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "folderId" TEXT REFERENCES "list_folders"("id") ON DELETE SET NULL, "name" TEXT NOT NULL, "colorHex" TEXT, "sortOrder" INTEGER NOT NULL, "isArchived" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL, "systemRole" TEXT, "visibleRootTaskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "completedAt" DATETIME);
CREATE INDEX "task_lists_on_workspaceId" ON "task_lists"("workspaceId");
CREATE INDEX "task_lists_on_folderId" ON "task_lists"("folderId");
CREATE TABLE "tasks" ("id" TEXT PRIMARY KEY, "listId" TEXT NOT NULL REFERENCES "task_lists"("id") ON DELETE CASCADE, "parentTaskId" TEXT REFERENCES "tasks"("id") ON DELETE CASCADE, "title" TEXT NOT NULL, "notes" TEXT NOT NULL DEFAULT '', "status" TEXT NOT NULL DEFAULT 'open', "sortOrder" INTEGER NOT NULL, "dueAt" DATETIME, "estimateSeconds" INTEGER, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL, "sourceSystem" TEXT, "sourceId" TEXT, "itemKind" TEXT, "isPromoted" BOOLEAN, "archivedAt" DATETIME, "completedAt" DATETIME);
CREATE INDEX "tasks_on_listId" ON "tasks"("listId");
CREATE INDEX "tasks_on_parentTaskId" ON "tasks"("parentTaskId");
CREATE TABLE "task_metadata" ("taskId" TEXT PRIMARY KEY REFERENCES "tasks"("id") ON DELETE CASCADE, "priority" INTEGER, "startAt" DATETIME, "tagsJSON" TEXT NOT NULL DEFAULT '[]', "recurrenceRule" TEXT, "matrixUrgency" INTEGER, "matrixImportance" INTEGER, "kanbanColumn" TEXT, "externalLinksJSON" TEXT NOT NULL DEFAULT '[]', "updatedAt" DATETIME NOT NULL, "focusRank" INTEGER, "planningJSON" TEXT);
CREATE TABLE "focus_sessions" ("id" TEXT PRIMARY KEY, "startedAt" DATETIME NOT NULL, "endedAt" DATETIME, "phase" TEXT NOT NULL, "activeTaskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "workDurationSeconds" INTEGER NOT NULL, "breakDurationSeconds" INTEGER NOT NULL, "breakEndsAt" DATETIME, "activeTaskStartedAt" DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00.000', "activeBlockId" TEXT, "accumulatedSeconds" INTEGER, "pausedAt" DATETIME, "checkpointAt" DATETIME);
CREATE INDEX "focus_sessions_on_startedAt" ON "focus_sessions"("startedAt");
CREATE TABLE "focus_queue_items" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "focus_sessions"("id") ON DELETE CASCADE, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "sortOrder" INTEGER NOT NULL, "state" TEXT NOT NULL DEFAULT 'queued', "completedAt" DATETIME, "skippedAt" DATETIME, "createdAt" DATETIME NOT NULL, "plannedSeconds" INTEGER);
CREATE INDEX "focus_queue_items_on_sessionId" ON "focus_queue_items"("sessionId");
CREATE INDEX "focus_queue_items_on_taskId" ON "focus_queue_items"("taskId");
CREATE TABLE "dailies" ("id" TEXT PRIMARY KEY, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "activeWeekdaysMask" INTEGER NOT NULL DEFAULT 127, "intervalDays" INTEGER, "intervalAnchor" DATETIME, "targetSeconds" INTEGER, "sortOrder" INTEGER NOT NULL, "archivedAt" DATETIME, "legacyDailyId" TEXT UNIQUE, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE INDEX "dailies_on_taskId" ON "dailies"("taskId");
CREATE TABLE "daily_contributions" ("id" TEXT PRIMARY KEY, "dailyId" TEXT NOT NULL REFERENCES "dailies"("id") ON DELETE CASCADE, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "dayKey" TEXT NOT NULL, "secondsLogged" INTEGER NOT NULL DEFAULT 0, "completedAt" DATETIME, "createdAt" DATETIME NOT NULL, UNIQUE ("dailyId", "dayKey"));
CREATE INDEX "daily_contributions_on_dailyId" ON "daily_contributions"("dailyId");
CREATE INDEX "daily_contributions_on_taskId" ON "daily_contributions"("taskId");
CREATE UNIQUE INDEX tasks_on_source
ON tasks(sourceSystem, sourceId) WHERE sourceId IS NOT NULL;
CREATE UNIQUE INDEX task_lists_on_system_role
ON task_lists(workspaceId, systemRole) WHERE systemRole IS NOT NULL;
CREATE VIRTUAL TABLE "tasks_fts" USING fts5(title, notes, tokenize='''porter'' ''unicode61''', content='tasks');
CREATE TRIGGER "__tasks_fts_ai" AFTER INSERT ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("rowid", "title", "notes") VALUES (new."rowid", new."title", new."notes");
END;
CREATE TRIGGER "__tasks_fts_ad" AFTER DELETE ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("tasks_fts", "rowid", "title", "notes") VALUES('delete', old."rowid", old."title", old."notes");
END;
CREATE TRIGGER "__tasks_fts_au" AFTER UPDATE ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("tasks_fts", "rowid", "title", "notes") VALUES('delete', old."rowid", old."title", old."notes");
    INSERT INTO "tasks_fts"("rowid", "title", "notes") VALUES (new."rowid", new."title", new."notes");
END;
CREATE TABLE "undo_control" ("id" INTEGER PRIMARY KEY, "groupId" TEXT, "label" TEXT, "suppressed" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE "change_log" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "groupId" TEXT, "label" TEXT, "tableName" TEXT NOT NULL, "rowId" TEXT NOT NULL, "operation" TEXT NOT NULL, "beforeJSON" TEXT, "afterJSON" TEXT, "undone" BOOLEAN NOT NULL DEFAULT 0);
CREATE INDEX "change_log_on_groupId" ON "change_log"("groupId");
CREATE TABLE "focus_awards" ("id" TEXT PRIMARY KEY, "sessionId" TEXT REFERENCES "focus_sessions"("id") ON DELETE SET NULL, "taskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "taskTitle" TEXT NOT NULL, "seconds" INTEGER NOT NULL, "minutes" DOUBLE NOT NULL, "multiplier" DOUBLE NOT NULL, "points" DOUBLE NOT NULL, "awardedAt" DATETIME NOT NULL);
CREATE INDEX "focus_awards_on_awardedAt" ON "focus_awards"("awardedAt");
CREATE TABLE "task_conditions" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "isLocation" BOOLEAN NOT NULL DEFAULT 0, "isArchived" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "focus_work_blocks" ("id" TEXT PRIMARY KEY, "sessionId" TEXT REFERENCES "focus_sessions"("id") ON DELETE SET NULL, "taskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "taskTitle" TEXT NOT NULL, "seconds" INTEGER NOT NULL, "recordedAt" DATETIME NOT NULL, "originalTaskId" TEXT);
CREATE INDEX "focus_work_blocks_on_taskId" ON "focus_work_blocks"("taskId");
CREATE INDEX "focus_work_blocks_on_originalTaskId" ON "focus_work_blocks"("originalTaskId");
CREATE TABLE "kanban_boards" ("id" TEXT PRIMARY KEY, "columnsJSON" TEXT NOT NULL);
CREATE TRIGGER change_log_task_lists_insert AFTER INSERT ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'folderId', NEW."folderId", 'name', NEW."name", 'colorHex', NEW."colorHex", 'sortOrder', NEW."sortOrder", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'systemRole', NEW."systemRole", 'visibleRootTaskId', NEW."visibleRootTaskId", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_task_lists_update AFTER UPDATE ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'folderId', OLD."folderId", 'name', OLD."name", 'colorHex', OLD."colorHex", 'sortOrder', OLD."sortOrder", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'systemRole', OLD."systemRole", 'visibleRootTaskId', OLD."visibleRootTaskId", 'completedAt', OLD."completedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'folderId', NEW."folderId", 'name', NEW."name", 'colorHex', NEW."colorHex", 'sortOrder', NEW."sortOrder", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'systemRole', NEW."systemRole", 'visibleRootTaskId', NEW."visibleRootTaskId", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_task_lists_delete AFTER DELETE ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'folderId', OLD."folderId", 'name', OLD."name", 'colorHex', OLD."colorHex", 'sortOrder', OLD."sortOrder", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'systemRole', OLD."systemRole", 'visibleRootTaskId', OLD."visibleRootTaskId", 'completedAt', OLD."completedAt"), NULL);
END;
CREATE TRIGGER change_log_list_folders_insert AFTER INSERT ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'parentFolderId', NEW."parentFolderId", 'name', NEW."name", 'sortOrder', NEW."sortOrder", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_list_folders_update AFTER UPDATE ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'parentFolderId', OLD."parentFolderId", 'name', OLD."name", 'sortOrder', OLD."sortOrder", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'parentFolderId', NEW."parentFolderId", 'name', NEW."name", 'sortOrder', NEW."sortOrder", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_list_folders_delete AFTER DELETE ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'parentFolderId', OLD."parentFolderId", 'name', OLD."name", 'sortOrder', OLD."sortOrder", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_tasks_insert AFTER INSERT ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'listId', NEW."listId", 'parentTaskId', NEW."parentTaskId", 'title', NEW."title", 'notes', NEW."notes", 'status', NEW."status", 'sortOrder', NEW."sortOrder", 'dueAt', NEW."dueAt", 'estimateSeconds', NEW."estimateSeconds", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'sourceSystem', NEW."sourceSystem", 'sourceId', NEW."sourceId", 'itemKind', NEW."itemKind", 'isPromoted', NEW."isPromoted", 'archivedAt', NEW."archivedAt", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_tasks_update AFTER UPDATE ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', NEW."id", 'update', json_object('id', OLD."id", 'listId', OLD."listId", 'parentTaskId', OLD."parentTaskId", 'title', OLD."title", 'notes', OLD."notes", 'status', OLD."status", 'sortOrder', OLD."sortOrder", 'dueAt', OLD."dueAt", 'estimateSeconds', OLD."estimateSeconds", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'sourceSystem', OLD."sourceSystem", 'sourceId', OLD."sourceId", 'itemKind', OLD."itemKind", 'isPromoted', OLD."isPromoted", 'archivedAt', OLD."archivedAt", 'completedAt', OLD."completedAt"), json_object('id', NEW."id", 'listId', NEW."listId", 'parentTaskId', NEW."parentTaskId", 'title', NEW."title", 'notes', NEW."notes", 'status', NEW."status", 'sortOrder', NEW."sortOrder", 'dueAt', NEW."dueAt", 'estimateSeconds', NEW."estimateSeconds", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'sourceSystem', NEW."sourceSystem", 'sourceId', NEW."sourceId", 'itemKind', NEW."itemKind", 'isPromoted', NEW."isPromoted", 'archivedAt', NEW."archivedAt", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_tasks_delete AFTER DELETE ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', OLD."id", 'delete', json_object('id', OLD."id", 'listId', OLD."listId", 'parentTaskId', OLD."parentTaskId", 'title', OLD."title", 'notes', OLD."notes", 'status', OLD."status", 'sortOrder', OLD."sortOrder", 'dueAt', OLD."dueAt", 'estimateSeconds', OLD."estimateSeconds", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'sourceSystem', OLD."sourceSystem", 'sourceId', OLD."sourceId", 'itemKind', OLD."itemKind", 'isPromoted', OLD."isPromoted", 'archivedAt', OLD."archivedAt", 'completedAt', OLD."completedAt"), NULL);
END;
CREATE TRIGGER change_log_task_metadata_insert AFTER INSERT ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', NEW."taskId", 'insert', NULL, json_object('taskId', NEW."taskId", 'priority', NEW."priority", 'startAt', NEW."startAt", 'tagsJSON', NEW."tagsJSON", 'recurrenceRule', NEW."recurrenceRule", 'matrixUrgency', NEW."matrixUrgency", 'matrixImportance', NEW."matrixImportance", 'kanbanColumn', NEW."kanbanColumn", 'externalLinksJSON', NEW."externalLinksJSON", 'updatedAt', NEW."updatedAt", 'focusRank', NEW."focusRank", 'planningJSON', NEW."planningJSON"));
END;
CREATE TRIGGER change_log_task_metadata_update AFTER UPDATE ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', NEW."taskId", 'update', json_object('taskId', OLD."taskId", 'priority', OLD."priority", 'startAt', OLD."startAt", 'tagsJSON', OLD."tagsJSON", 'recurrenceRule', OLD."recurrenceRule", 'matrixUrgency', OLD."matrixUrgency", 'matrixImportance', OLD."matrixImportance", 'kanbanColumn', OLD."kanbanColumn", 'externalLinksJSON', OLD."externalLinksJSON", 'updatedAt', OLD."updatedAt", 'focusRank', OLD."focusRank", 'planningJSON', OLD."planningJSON"), json_object('taskId', NEW."taskId", 'priority', NEW."priority", 'startAt', NEW."startAt", 'tagsJSON', NEW."tagsJSON", 'recurrenceRule', NEW."recurrenceRule", 'matrixUrgency', NEW."matrixUrgency", 'matrixImportance', NEW."matrixImportance", 'kanbanColumn', NEW."kanbanColumn", 'externalLinksJSON', NEW."externalLinksJSON", 'updatedAt', NEW."updatedAt", 'focusRank', NEW."focusRank", 'planningJSON', NEW."planningJSON"));
END;
CREATE TRIGGER change_log_task_metadata_delete AFTER DELETE ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', OLD."taskId", 'delete', json_object('taskId', OLD."taskId", 'priority', OLD."priority", 'startAt', OLD."startAt", 'tagsJSON', OLD."tagsJSON", 'recurrenceRule', OLD."recurrenceRule", 'matrixUrgency', OLD."matrixUrgency", 'matrixImportance', OLD."matrixImportance", 'kanbanColumn', OLD."kanbanColumn", 'externalLinksJSON', OLD."externalLinksJSON", 'updatedAt', OLD."updatedAt", 'focusRank', OLD."focusRank", 'planningJSON', OLD."planningJSON"), NULL);
END;
CREATE TRIGGER change_log_task_conditions_insert AFTER INSERT ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'name', NEW."name", 'isLocation', NEW."isLocation", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_task_conditions_update AFTER UPDATE ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'name', OLD."name", 'isLocation', OLD."isLocation", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'name', NEW."name", 'isLocation', NEW."isLocation", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_task_conditions_delete AFTER DELETE ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'name', OLD."name", 'isLocation', OLD."isLocation", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_dailies_insert AFTER INSERT ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'taskId', NEW."taskId", 'activeWeekdaysMask', NEW."activeWeekdaysMask", 'intervalDays', NEW."intervalDays", 'intervalAnchor', NEW."intervalAnchor", 'targetSeconds', NEW."targetSeconds", 'sortOrder', NEW."sortOrder", 'archivedAt', NEW."archivedAt", 'legacyDailyId', NEW."legacyDailyId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_dailies_update AFTER UPDATE ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', NEW."id", 'update', json_object('id', OLD."id", 'taskId', OLD."taskId", 'activeWeekdaysMask', OLD."activeWeekdaysMask", 'intervalDays', OLD."intervalDays", 'intervalAnchor', OLD."intervalAnchor", 'targetSeconds', OLD."targetSeconds", 'sortOrder', OLD."sortOrder", 'archivedAt', OLD."archivedAt", 'legacyDailyId', OLD."legacyDailyId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'taskId', NEW."taskId", 'activeWeekdaysMask', NEW."activeWeekdaysMask", 'intervalDays', NEW."intervalDays", 'intervalAnchor', NEW."intervalAnchor", 'targetSeconds', NEW."targetSeconds", 'sortOrder', NEW."sortOrder", 'archivedAt', NEW."archivedAt", 'legacyDailyId', NEW."legacyDailyId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_dailies_delete AFTER DELETE ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', OLD."id", 'delete', json_object('id', OLD."id", 'taskId', OLD."taskId", 'activeWeekdaysMask', OLD."activeWeekdaysMask", 'intervalDays', OLD."intervalDays", 'intervalAnchor', OLD."intervalAnchor", 'targetSeconds', OLD."targetSeconds", 'sortOrder', OLD."sortOrder", 'archivedAt', OLD."archivedAt", 'legacyDailyId', OLD."legacyDailyId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_daily_contributions_insert AFTER INSERT ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'dailyId', NEW."dailyId", 'taskId', NEW."taskId", 'dayKey', NEW."dayKey", 'secondsLogged', NEW."secondsLogged", 'completedAt', NEW."completedAt", 'createdAt', NEW."createdAt"));
END;
CREATE TRIGGER change_log_daily_contributions_update AFTER UPDATE ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', NEW."id", 'update', json_object('id', OLD."id", 'dailyId', OLD."dailyId", 'taskId', OLD."taskId", 'dayKey', OLD."dayKey", 'secondsLogged', OLD."secondsLogged", 'completedAt', OLD."completedAt", 'createdAt', OLD."createdAt"), json_object('id', NEW."id", 'dailyId', NEW."dailyId", 'taskId', NEW."taskId", 'dayKey', NEW."dayKey", 'secondsLogged', NEW."secondsLogged", 'completedAt', NEW."completedAt", 'createdAt', NEW."createdAt"));
END;
CREATE TRIGGER change_log_daily_contributions_delete AFTER DELETE ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', OLD."id", 'delete', json_object('id', OLD."id", 'dailyId', OLD."dailyId", 'taskId', OLD."taskId", 'dayKey', OLD."dayKey", 'secondsLogged', OLD."secondsLogged", 'completedAt', OLD."completedAt", 'createdAt', OLD."createdAt"), NULL);
END;
CREATE TRIGGER change_log_kanban_boards_insert AFTER INSERT ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'columnsJSON', NEW."columnsJSON"));
END;
CREATE TRIGGER change_log_kanban_boards_update AFTER UPDATE ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', NEW."id", 'update', json_object('id', OLD."id", 'columnsJSON', OLD."columnsJSON"), json_object('id', NEW."id", 'columnsJSON', NEW."columnsJSON"));
END;
CREATE TRIGGER change_log_kanban_boards_delete AFTER DELETE ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', OLD."id", 'delete', json_object('id', OLD."id", 'columnsJSON', OLD."columnsJSON"), NULL);
END;
CREATE TABLE sync_control (
  id INTEGER PRIMARY KEY,
  recording INTEGER NOT NULL DEFAULT 0,
  applying INTEGER NOT NULL DEFAULT 0);
CREATE TABLE sync_outbox (
  seq INTEGER PRIMARY KEY AUTOINCREMENT,
  tableName TEXT NOT NULL,
  rowId TEXT NOT NULL,
  operation TEXT NOT NULL,
  changedJSON TEXT,
  changedAtMs INTEGER NOT NULL);
CREATE INDEX sync_outbox_on_row ON sync_outbox(tableName, rowId);
CREATE TABLE sync_state (
  id INTEGER PRIMARY KEY,
  deviceId TEXT NOT NULL,
  cursor INTEGER NOT NULL DEFAULT 0,
  hlc TEXT,
  serverURL TEXT,
  canonicalWorkspaceId TEXT,
  needsSnapshot INTEGER NOT NULL DEFAULT 1,
  lastSyncedAt DATETIME);
CREATE TABLE themes (
  id TEXT PRIMARY KEY,
  json TEXT NOT NULL,
  updatedAt DATETIME NOT NULL);
CREATE TABLE preferences (
  key TEXT PRIMARY KEY,
  value TEXT,
  updatedAt DATETIME NOT NULL);
CREATE TRIGGER sync_outbox_workspaces_insert AFTER INSERT ON workspaces WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('workspaces', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_workspaces_update AFTER UPDATE ON workspaces WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('workspaces', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."name" IS NOT NEW."name" THEN 'name' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_workspaces_delete AFTER DELETE ON workspaces WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('workspaces', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_list_folders_insert AFTER INSERT ON list_folders WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('list_folders', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_list_folders_update AFTER UPDATE ON list_folders WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('list_folders', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."workspaceId" IS NOT NEW."workspaceId" THEN 'workspaceId' END, CASE WHEN OLD."parentFolderId" IS NOT NEW."parentFolderId" THEN 'parentFolderId' END, CASE WHEN OLD."name" IS NOT NEW."name" THEN 'name' END, CASE WHEN OLD."sortOrder" IS NOT NEW."sortOrder" THEN 'sortOrder' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_list_folders_delete AFTER DELETE ON list_folders WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('list_folders', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_lists_insert AFTER INSERT ON task_lists WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_lists', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_lists_update AFTER UPDATE ON task_lists WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_lists', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."workspaceId" IS NOT NEW."workspaceId" THEN 'workspaceId' END, CASE WHEN OLD."folderId" IS NOT NEW."folderId" THEN 'folderId' END, CASE WHEN OLD."name" IS NOT NEW."name" THEN 'name' END, CASE WHEN OLD."colorHex" IS NOT NEW."colorHex" THEN 'colorHex' END, CASE WHEN OLD."sortOrder" IS NOT NEW."sortOrder" THEN 'sortOrder' END, CASE WHEN OLD."isArchived" IS NOT NEW."isArchived" THEN 'isArchived' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END, CASE WHEN OLD."systemRole" IS NOT NEW."systemRole" THEN 'systemRole' END, CASE WHEN OLD."visibleRootTaskId" IS NOT NEW."visibleRootTaskId" THEN 'visibleRootTaskId' END, CASE WHEN OLD."completedAt" IS NOT NEW."completedAt" THEN 'completedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_lists_delete AFTER DELETE ON task_lists WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_lists', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_tasks_insert AFTER INSERT ON tasks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('tasks', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_tasks_update AFTER UPDATE ON tasks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('tasks', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."listId" IS NOT NEW."listId" THEN 'listId' END, CASE WHEN OLD."parentTaskId" IS NOT NEW."parentTaskId" THEN 'parentTaskId' END, CASE WHEN OLD."title" IS NOT NEW."title" THEN 'title' END, CASE WHEN OLD."notes" IS NOT NEW."notes" THEN 'notes' END, CASE WHEN OLD."status" IS NOT NEW."status" THEN 'status' END, CASE WHEN OLD."sortOrder" IS NOT NEW."sortOrder" THEN 'sortOrder' END, CASE WHEN OLD."dueAt" IS NOT NEW."dueAt" THEN 'dueAt' END, CASE WHEN OLD."estimateSeconds" IS NOT NEW."estimateSeconds" THEN 'estimateSeconds' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END, CASE WHEN OLD."sourceSystem" IS NOT NEW."sourceSystem" THEN 'sourceSystem' END, CASE WHEN OLD."sourceId" IS NOT NEW."sourceId" THEN 'sourceId' END, CASE WHEN OLD."itemKind" IS NOT NEW."itemKind" THEN 'itemKind' END, CASE WHEN OLD."isPromoted" IS NOT NEW."isPromoted" THEN 'isPromoted' END, CASE WHEN OLD."archivedAt" IS NOT NEW."archivedAt" THEN 'archivedAt' END, CASE WHEN OLD."completedAt" IS NOT NEW."completedAt" THEN 'completedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_tasks_delete AFTER DELETE ON tasks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('tasks', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_metadata_insert AFTER INSERT ON task_metadata WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_metadata', NEW."taskId", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_metadata_update AFTER UPDATE ON task_metadata WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_metadata', NEW."taskId", 'update', json_array(CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."priority" IS NOT NEW."priority" THEN 'priority' END, CASE WHEN OLD."startAt" IS NOT NEW."startAt" THEN 'startAt' END, CASE WHEN OLD."tagsJSON" IS NOT NEW."tagsJSON" THEN 'tagsJSON' END, CASE WHEN OLD."recurrenceRule" IS NOT NEW."recurrenceRule" THEN 'recurrenceRule' END, CASE WHEN OLD."matrixUrgency" IS NOT NEW."matrixUrgency" THEN 'matrixUrgency' END, CASE WHEN OLD."matrixImportance" IS NOT NEW."matrixImportance" THEN 'matrixImportance' END, CASE WHEN OLD."kanbanColumn" IS NOT NEW."kanbanColumn" THEN 'kanbanColumn' END, CASE WHEN OLD."externalLinksJSON" IS NOT NEW."externalLinksJSON" THEN 'externalLinksJSON' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END, CASE WHEN OLD."focusRank" IS NOT NEW."focusRank" THEN 'focusRank' END, CASE WHEN OLD."planningJSON" IS NOT NEW."planningJSON" THEN 'planningJSON' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_metadata_delete AFTER DELETE ON task_metadata WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_metadata', OLD."taskId", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_conditions_insert AFTER INSERT ON task_conditions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_conditions', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_conditions_update AFTER UPDATE ON task_conditions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_conditions', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."workspaceId" IS NOT NEW."workspaceId" THEN 'workspaceId' END, CASE WHEN OLD."name" IS NOT NEW."name" THEN 'name' END, CASE WHEN OLD."isLocation" IS NOT NEW."isLocation" THEN 'isLocation' END, CASE WHEN OLD."isArchived" IS NOT NEW."isArchived" THEN 'isArchived' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_task_conditions_delete AFTER DELETE ON task_conditions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('task_conditions', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_kanban_boards_insert AFTER INSERT ON kanban_boards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('kanban_boards', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_kanban_boards_update AFTER UPDATE ON kanban_boards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('kanban_boards', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."columnsJSON" IS NOT NEW."columnsJSON" THEN 'columnsJSON' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_kanban_boards_delete AFTER DELETE ON kanban_boards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('kanban_boards', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_dailies_insert AFTER INSERT ON dailies WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('dailies', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_dailies_update AFTER UPDATE ON dailies WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('dailies', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."activeWeekdaysMask" IS NOT NEW."activeWeekdaysMask" THEN 'activeWeekdaysMask' END, CASE WHEN OLD."intervalDays" IS NOT NEW."intervalDays" THEN 'intervalDays' END, CASE WHEN OLD."intervalAnchor" IS NOT NEW."intervalAnchor" THEN 'intervalAnchor' END, CASE WHEN OLD."targetSeconds" IS NOT NEW."targetSeconds" THEN 'targetSeconds' END, CASE WHEN OLD."sortOrder" IS NOT NEW."sortOrder" THEN 'sortOrder' END, CASE WHEN OLD."archivedAt" IS NOT NEW."archivedAt" THEN 'archivedAt' END, CASE WHEN OLD."legacyDailyId" IS NOT NEW."legacyDailyId" THEN 'legacyDailyId' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_dailies_delete AFTER DELETE ON dailies WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('dailies', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_daily_contributions_insert AFTER INSERT ON daily_contributions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('daily_contributions', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_daily_contributions_update AFTER UPDATE ON daily_contributions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('daily_contributions', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."dailyId" IS NOT NEW."dailyId" THEN 'dailyId' END, CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."dayKey" IS NOT NEW."dayKey" THEN 'dayKey' END, CASE WHEN OLD."secondsLogged" IS NOT NEW."secondsLogged" THEN 'secondsLogged' END, CASE WHEN OLD."completedAt" IS NOT NEW."completedAt" THEN 'completedAt' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_daily_contributions_delete AFTER DELETE ON daily_contributions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('daily_contributions', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_sessions_insert AFTER INSERT ON focus_sessions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_sessions', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_sessions_update AFTER UPDATE ON focus_sessions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_sessions', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."startedAt" IS NOT NEW."startedAt" THEN 'startedAt' END, CASE WHEN OLD."endedAt" IS NOT NEW."endedAt" THEN 'endedAt' END, CASE WHEN OLD."phase" IS NOT NEW."phase" THEN 'phase' END, CASE WHEN OLD."activeTaskId" IS NOT NEW."activeTaskId" THEN 'activeTaskId' END, CASE WHEN OLD."workDurationSeconds" IS NOT NEW."workDurationSeconds" THEN 'workDurationSeconds' END, CASE WHEN OLD."breakDurationSeconds" IS NOT NEW."breakDurationSeconds" THEN 'breakDurationSeconds' END, CASE WHEN OLD."breakEndsAt" IS NOT NEW."breakEndsAt" THEN 'breakEndsAt' END, CASE WHEN OLD."activeTaskStartedAt" IS NOT NEW."activeTaskStartedAt" THEN 'activeTaskStartedAt' END, CASE WHEN OLD."activeBlockId" IS NOT NEW."activeBlockId" THEN 'activeBlockId' END, CASE WHEN OLD."accumulatedSeconds" IS NOT NEW."accumulatedSeconds" THEN 'accumulatedSeconds' END, CASE WHEN OLD."pausedAt" IS NOT NEW."pausedAt" THEN 'pausedAt' END, CASE WHEN OLD."checkpointAt" IS NOT NEW."checkpointAt" THEN 'checkpointAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_sessions_delete AFTER DELETE ON focus_sessions WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_sessions', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_queue_items_insert AFTER INSERT ON focus_queue_items WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_queue_items', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_queue_items_update AFTER UPDATE ON focus_queue_items WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_queue_items', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."sessionId" IS NOT NEW."sessionId" THEN 'sessionId' END, CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."sortOrder" IS NOT NEW."sortOrder" THEN 'sortOrder' END, CASE WHEN OLD."state" IS NOT NEW."state" THEN 'state' END, CASE WHEN OLD."completedAt" IS NOT NEW."completedAt" THEN 'completedAt' END, CASE WHEN OLD."skippedAt" IS NOT NEW."skippedAt" THEN 'skippedAt' END, CASE WHEN OLD."createdAt" IS NOT NEW."createdAt" THEN 'createdAt' END, CASE WHEN OLD."plannedSeconds" IS NOT NEW."plannedSeconds" THEN 'plannedSeconds' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_queue_items_delete AFTER DELETE ON focus_queue_items WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_queue_items', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_work_blocks_insert AFTER INSERT ON focus_work_blocks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_work_blocks', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_work_blocks_update AFTER UPDATE ON focus_work_blocks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_work_blocks', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."sessionId" IS NOT NEW."sessionId" THEN 'sessionId' END, CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."taskTitle" IS NOT NEW."taskTitle" THEN 'taskTitle' END, CASE WHEN OLD."seconds" IS NOT NEW."seconds" THEN 'seconds' END, CASE WHEN OLD."recordedAt" IS NOT NEW."recordedAt" THEN 'recordedAt' END, CASE WHEN OLD."originalTaskId" IS NOT NEW."originalTaskId" THEN 'originalTaskId' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_work_blocks_delete AFTER DELETE ON focus_work_blocks WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_work_blocks', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_awards_insert AFTER INSERT ON focus_awards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_awards', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_awards_update AFTER UPDATE ON focus_awards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_awards', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."sessionId" IS NOT NEW."sessionId" THEN 'sessionId' END, CASE WHEN OLD."taskId" IS NOT NEW."taskId" THEN 'taskId' END, CASE WHEN OLD."taskTitle" IS NOT NEW."taskTitle" THEN 'taskTitle' END, CASE WHEN OLD."seconds" IS NOT NEW."seconds" THEN 'seconds' END, CASE WHEN OLD."minutes" IS NOT NEW."minutes" THEN 'minutes' END, CASE WHEN OLD."multiplier" IS NOT NEW."multiplier" THEN 'multiplier' END, CASE WHEN OLD."points" IS NOT NEW."points" THEN 'points' END, CASE WHEN OLD."awardedAt" IS NOT NEW."awardedAt" THEN 'awardedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_focus_awards_delete AFTER DELETE ON focus_awards WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('focus_awards', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_themes_insert AFTER INSERT ON themes WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('themes', NEW."id", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_themes_update AFTER UPDATE ON themes WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('themes', NEW."id", 'update', json_array(CASE WHEN OLD."id" IS NOT NEW."id" THEN 'id' END, CASE WHEN OLD."json" IS NOT NEW."json" THEN 'json' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_themes_delete AFTER DELETE ON themes WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('themes', OLD."id", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_preferences_insert AFTER INSERT ON preferences WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('preferences', NEW."key", 'insert', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_preferences_update AFTER UPDATE ON preferences WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('preferences', NEW."key", 'update', json_array(CASE WHEN OLD."key" IS NOT NEW."key" THEN 'key' END, CASE WHEN OLD."value" IS NOT NEW."value" THEN 'value' END, CASE WHEN OLD."updatedAt" IS NOT NEW."updatedAt" THEN 'updatedAt' END), CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;
CREATE TRIGGER sync_outbox_preferences_delete AFTER DELETE ON preferences WHEN (SELECT recording FROM sync_control WHERE id = 0) = 1
  AND (SELECT applying FROM sync_control WHERE id = 0) = 0
BEGIN INSERT INTO sync_outbox(tableName, rowId, operation, changedJSON, changedAtMs) VALUES ('preferences', OLD."key", 'delete', NULL, CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)); END;

-- The migration ledger, so a fixture reads as migrated.
INSERT INTO grdb_migrations (identifier) VALUES ('v1_local_workspace');
INSERT INTO grdb_migrations (identifier) VALUES ('v2_metadata_and_focus');
INSERT INTO grdb_migrations (identifier) VALUES ('v3_dailies_as_contributions');
INSERT INTO grdb_migrations (identifier) VALUES ('v4_manual_focus_order');
INSERT INTO grdb_migrations (identifier) VALUES ('v5_task_source_identity');
INSERT INTO grdb_migrations (identifier) VALUES ('v6_inbox_as_a_system_list');
INSERT INTO grdb_migrations (identifier) VALUES ('v7_task_full_text_search');
INSERT INTO grdb_migrations (identifier) VALUES ('v8_undo_journal');
INSERT INTO grdb_migrations (identifier) VALUES ('v9_focus_block_start');
INSERT INTO grdb_migrations (identifier) VALUES ('v10_focus_points');
INSERT INTO grdb_migrations (identifier) VALUES ('v11_stable_visible_roots');
INSERT INTO grdb_migrations (identifier) VALUES ('v12_task_conditions_and_work');
INSERT INTO grdb_migrations (identifier) VALUES ('v13_legacy_visible_roots');
INSERT INTO grdb_migrations (identifier) VALUES ('v14_nested_lists');
INSERT INTO grdb_migrations (identifier) VALUES ('v15_kanban_board_history');
INSERT INTO grdb_migrations (identifier) VALUES ('v16_task_completion_time');
INSERT INTO grdb_migrations (identifier) VALUES ('v17_sync');
INSERT INTO grdb_migrations (identifier) VALUES ('v18_themes_and_preferences');
INSERT INTO undo_control (id, suppressed) VALUES (0, 1);
INSERT INTO sync_control (id) VALUES (0);
