-- The app's workspace schema, DDL only, as of v16_task_completion_time.
-- Generated by scripts/dump_workspace_schema.sh; do not edit by hand.
CREATE TABLE grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY);
CREATE TABLE "workspaces" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "list_folders" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "parentFolderId" TEXT REFERENCES "list_folders"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE INDEX "list_folders_on_workspaceId" ON "list_folders"("workspaceId");
CREATE INDEX "list_folders_on_parentFolderId" ON "list_folders"("parentFolderId");
CREATE TABLE "task_lists" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "folderId" TEXT REFERENCES "list_folders"("id") ON DELETE SET NULL, "name" TEXT NOT NULL, "colorHex" TEXT, "sortOrder" INTEGER NOT NULL, "isArchived" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL, "systemRole" TEXT, "visibleRootTaskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "completedAt" DATETIME);
CREATE INDEX "task_lists_on_workspaceId" ON "task_lists"("workspaceId");
CREATE INDEX "task_lists_on_folderId" ON "task_lists"("folderId");
CREATE TABLE "tasks" ("id" TEXT PRIMARY KEY, "listId" TEXT NOT NULL REFERENCES "task_lists"("id") ON DELETE CASCADE, "parentTaskId" TEXT REFERENCES "tasks"("id") ON DELETE CASCADE, "title" TEXT NOT NULL, "notes" TEXT NOT NULL DEFAULT '', "status" TEXT NOT NULL DEFAULT 'open', "sortOrder" INTEGER NOT NULL, "dueAt" DATETIME, "estimateSeconds" INTEGER, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL, "sourceSystem" TEXT, "sourceId" TEXT, "itemKind" TEXT, "isPromoted" BOOLEAN, "archivedAt" DATETIME, "completedAt" DATETIME);
CREATE INDEX "tasks_on_listId" ON "tasks"("listId");
CREATE INDEX "tasks_on_parentTaskId" ON "tasks"("parentTaskId");
CREATE TABLE "task_metadata" ("taskId" TEXT PRIMARY KEY REFERENCES "tasks"("id") ON DELETE CASCADE, "priority" INTEGER, "startAt" DATETIME, "tagsJSON" TEXT NOT NULL DEFAULT '[]', "recurrenceRule" TEXT, "matrixUrgency" INTEGER, "matrixImportance" INTEGER, "kanbanColumn" TEXT, "externalLinksJSON" TEXT NOT NULL DEFAULT '[]', "updatedAt" DATETIME NOT NULL, "focusRank" INTEGER, "planningJSON" TEXT);
CREATE TABLE "focus_sessions" ("id" TEXT PRIMARY KEY, "startedAt" DATETIME NOT NULL, "endedAt" DATETIME, "phase" TEXT NOT NULL, "activeTaskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "workDurationSeconds" INTEGER NOT NULL, "breakDurationSeconds" INTEGER NOT NULL, "breakEndsAt" DATETIME, "activeTaskStartedAt" DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00.000', "activeBlockId" TEXT, "accumulatedSeconds" INTEGER, "pausedAt" DATETIME, "checkpointAt" DATETIME);
CREATE INDEX "focus_sessions_on_startedAt" ON "focus_sessions"("startedAt");
CREATE TABLE "focus_queue_items" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "focus_sessions"("id") ON DELETE CASCADE, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "sortOrder" INTEGER NOT NULL, "state" TEXT NOT NULL DEFAULT 'queued', "completedAt" DATETIME, "skippedAt" DATETIME, "createdAt" DATETIME NOT NULL, "plannedSeconds" INTEGER);
CREATE INDEX "focus_queue_items_on_sessionId" ON "focus_queue_items"("sessionId");
CREATE INDEX "focus_queue_items_on_taskId" ON "focus_queue_items"("taskId");
CREATE TABLE "dailies" ("id" TEXT PRIMARY KEY, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "activeWeekdaysMask" INTEGER NOT NULL DEFAULT 127, "intervalDays" INTEGER, "intervalAnchor" DATETIME, "targetSeconds" INTEGER, "sortOrder" INTEGER NOT NULL, "archivedAt" DATETIME, "legacyDailyId" TEXT UNIQUE, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE INDEX "dailies_on_taskId" ON "dailies"("taskId");
CREATE TABLE "daily_contributions" ("id" TEXT PRIMARY KEY, "dailyId" TEXT NOT NULL REFERENCES "dailies"("id") ON DELETE CASCADE, "taskId" TEXT NOT NULL REFERENCES "tasks"("id") ON DELETE CASCADE, "dayKey" TEXT NOT NULL, "secondsLogged" INTEGER NOT NULL DEFAULT 0, "completedAt" DATETIME, "createdAt" DATETIME NOT NULL, UNIQUE ("dailyId", "dayKey"));
CREATE INDEX "daily_contributions_on_dailyId" ON "daily_contributions"("dailyId");
CREATE INDEX "daily_contributions_on_taskId" ON "daily_contributions"("taskId");
CREATE UNIQUE INDEX tasks_on_source
ON tasks(sourceSystem, sourceId) WHERE sourceId IS NOT NULL;
CREATE UNIQUE INDEX task_lists_on_system_role
ON task_lists(workspaceId, systemRole) WHERE systemRole IS NOT NULL;
CREATE VIRTUAL TABLE "tasks_fts" USING fts5(title, notes, tokenize='''porter'' ''unicode61''', content='tasks');
CREATE TRIGGER "__tasks_fts_ai" AFTER INSERT ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("rowid", "title", "notes") VALUES (new."rowid", new."title", new."notes");
END;
CREATE TRIGGER "__tasks_fts_ad" AFTER DELETE ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("tasks_fts", "rowid", "title", "notes") VALUES('delete', old."rowid", old."title", old."notes");
END;
CREATE TRIGGER "__tasks_fts_au" AFTER UPDATE ON "tasks" BEGIN
    INSERT INTO "tasks_fts"("tasks_fts", "rowid", "title", "notes") VALUES('delete', old."rowid", old."title", old."notes");
    INSERT INTO "tasks_fts"("rowid", "title", "notes") VALUES (new."rowid", new."title", new."notes");
END;
CREATE TABLE "undo_control" ("id" INTEGER PRIMARY KEY, "groupId" TEXT, "label" TEXT, "suppressed" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE "change_log" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "groupId" TEXT, "label" TEXT, "tableName" TEXT NOT NULL, "rowId" TEXT NOT NULL, "operation" TEXT NOT NULL, "beforeJSON" TEXT, "afterJSON" TEXT, "undone" BOOLEAN NOT NULL DEFAULT 0);
CREATE INDEX "change_log_on_groupId" ON "change_log"("groupId");
CREATE TABLE "focus_awards" ("id" TEXT PRIMARY KEY, "sessionId" TEXT REFERENCES "focus_sessions"("id") ON DELETE SET NULL, "taskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "taskTitle" TEXT NOT NULL, "seconds" INTEGER NOT NULL, "minutes" DOUBLE NOT NULL, "multiplier" DOUBLE NOT NULL, "points" DOUBLE NOT NULL, "awardedAt" DATETIME NOT NULL);
CREATE INDEX "focus_awards_on_awardedAt" ON "focus_awards"("awardedAt");
CREATE TABLE "task_conditions" ("id" TEXT PRIMARY KEY, "workspaceId" TEXT NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "isLocation" BOOLEAN NOT NULL DEFAULT 0, "isArchived" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "focus_work_blocks" ("id" TEXT PRIMARY KEY, "sessionId" TEXT REFERENCES "focus_sessions"("id") ON DELETE SET NULL, "taskId" TEXT REFERENCES "tasks"("id") ON DELETE SET NULL, "taskTitle" TEXT NOT NULL, "seconds" INTEGER NOT NULL, "recordedAt" DATETIME NOT NULL, "originalTaskId" TEXT);
CREATE INDEX "focus_work_blocks_on_taskId" ON "focus_work_blocks"("taskId");
CREATE INDEX "focus_work_blocks_on_originalTaskId" ON "focus_work_blocks"("originalTaskId");
CREATE TABLE "kanban_boards" ("id" TEXT PRIMARY KEY, "columnsJSON" TEXT NOT NULL);
CREATE TRIGGER change_log_task_lists_insert AFTER INSERT ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'folderId', NEW."folderId", 'name', NEW."name", 'colorHex', NEW."colorHex", 'sortOrder', NEW."sortOrder", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'systemRole', NEW."systemRole", 'visibleRootTaskId', NEW."visibleRootTaskId", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_task_lists_update AFTER UPDATE ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'folderId', OLD."folderId", 'name', OLD."name", 'colorHex', OLD."colorHex", 'sortOrder', OLD."sortOrder", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'systemRole', OLD."systemRole", 'visibleRootTaskId', OLD."visibleRootTaskId", 'completedAt', OLD."completedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'folderId', NEW."folderId", 'name', NEW."name", 'colorHex', NEW."colorHex", 'sortOrder', NEW."sortOrder", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'systemRole', NEW."systemRole", 'visibleRootTaskId', NEW."visibleRootTaskId", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_task_lists_delete AFTER DELETE ON task_lists WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_lists', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'folderId', OLD."folderId", 'name', OLD."name", 'colorHex', OLD."colorHex", 'sortOrder', OLD."sortOrder", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'systemRole', OLD."systemRole", 'visibleRootTaskId', OLD."visibleRootTaskId", 'completedAt', OLD."completedAt"), NULL);
END;
CREATE TRIGGER change_log_list_folders_insert AFTER INSERT ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'parentFolderId', NEW."parentFolderId", 'name', NEW."name", 'sortOrder', NEW."sortOrder", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_list_folders_update AFTER UPDATE ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'parentFolderId', OLD."parentFolderId", 'name', OLD."name", 'sortOrder', OLD."sortOrder", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'parentFolderId', NEW."parentFolderId", 'name', NEW."name", 'sortOrder', NEW."sortOrder", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_list_folders_delete AFTER DELETE ON list_folders WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'list_folders', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'parentFolderId', OLD."parentFolderId", 'name', OLD."name", 'sortOrder', OLD."sortOrder", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_tasks_insert AFTER INSERT ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'listId', NEW."listId", 'parentTaskId', NEW."parentTaskId", 'title', NEW."title", 'notes', NEW."notes", 'status', NEW."status", 'sortOrder', NEW."sortOrder", 'dueAt', NEW."dueAt", 'estimateSeconds', NEW."estimateSeconds", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'sourceSystem', NEW."sourceSystem", 'sourceId', NEW."sourceId", 'itemKind', NEW."itemKind", 'isPromoted', NEW."isPromoted", 'archivedAt', NEW."archivedAt", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_tasks_update AFTER UPDATE ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', NEW."id", 'update', json_object('id', OLD."id", 'listId', OLD."listId", 'parentTaskId', OLD."parentTaskId", 'title', OLD."title", 'notes', OLD."notes", 'status', OLD."status", 'sortOrder', OLD."sortOrder", 'dueAt', OLD."dueAt", 'estimateSeconds', OLD."estimateSeconds", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'sourceSystem', OLD."sourceSystem", 'sourceId', OLD."sourceId", 'itemKind', OLD."itemKind", 'isPromoted', OLD."isPromoted", 'archivedAt', OLD."archivedAt", 'completedAt', OLD."completedAt"), json_object('id', NEW."id", 'listId', NEW."listId", 'parentTaskId', NEW."parentTaskId", 'title', NEW."title", 'notes', NEW."notes", 'status', NEW."status", 'sortOrder', NEW."sortOrder", 'dueAt', NEW."dueAt", 'estimateSeconds', NEW."estimateSeconds", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt", 'sourceSystem', NEW."sourceSystem", 'sourceId', NEW."sourceId", 'itemKind', NEW."itemKind", 'isPromoted', NEW."isPromoted", 'archivedAt', NEW."archivedAt", 'completedAt', NEW."completedAt"));
END;
CREATE TRIGGER change_log_tasks_delete AFTER DELETE ON tasks WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'tasks', OLD."id", 'delete', json_object('id', OLD."id", 'listId', OLD."listId", 'parentTaskId', OLD."parentTaskId", 'title', OLD."title", 'notes', OLD."notes", 'status', OLD."status", 'sortOrder', OLD."sortOrder", 'dueAt', OLD."dueAt", 'estimateSeconds', OLD."estimateSeconds", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt", 'sourceSystem', OLD."sourceSystem", 'sourceId', OLD."sourceId", 'itemKind', OLD."itemKind", 'isPromoted', OLD."isPromoted", 'archivedAt', OLD."archivedAt", 'completedAt', OLD."completedAt"), NULL);
END;
CREATE TRIGGER change_log_task_metadata_insert AFTER INSERT ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', NEW."taskId", 'insert', NULL, json_object('taskId', NEW."taskId", 'priority', NEW."priority", 'startAt', NEW."startAt", 'tagsJSON', NEW."tagsJSON", 'recurrenceRule', NEW."recurrenceRule", 'matrixUrgency', NEW."matrixUrgency", 'matrixImportance', NEW."matrixImportance", 'kanbanColumn', NEW."kanbanColumn", 'externalLinksJSON', NEW."externalLinksJSON", 'updatedAt', NEW."updatedAt", 'focusRank', NEW."focusRank", 'planningJSON', NEW."planningJSON"));
END;
CREATE TRIGGER change_log_task_metadata_update AFTER UPDATE ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', NEW."taskId", 'update', json_object('taskId', OLD."taskId", 'priority', OLD."priority", 'startAt', OLD."startAt", 'tagsJSON', OLD."tagsJSON", 'recurrenceRule', OLD."recurrenceRule", 'matrixUrgency', OLD."matrixUrgency", 'matrixImportance', OLD."matrixImportance", 'kanbanColumn', OLD."kanbanColumn", 'externalLinksJSON', OLD."externalLinksJSON", 'updatedAt', OLD."updatedAt", 'focusRank', OLD."focusRank", 'planningJSON', OLD."planningJSON"), json_object('taskId', NEW."taskId", 'priority', NEW."priority", 'startAt', NEW."startAt", 'tagsJSON', NEW."tagsJSON", 'recurrenceRule', NEW."recurrenceRule", 'matrixUrgency', NEW."matrixUrgency", 'matrixImportance', NEW."matrixImportance", 'kanbanColumn', NEW."kanbanColumn", 'externalLinksJSON', NEW."externalLinksJSON", 'updatedAt', NEW."updatedAt", 'focusRank', NEW."focusRank", 'planningJSON', NEW."planningJSON"));
END;
CREATE TRIGGER change_log_task_metadata_delete AFTER DELETE ON task_metadata WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_metadata', OLD."taskId", 'delete', json_object('taskId', OLD."taskId", 'priority', OLD."priority", 'startAt', OLD."startAt", 'tagsJSON', OLD."tagsJSON", 'recurrenceRule', OLD."recurrenceRule", 'matrixUrgency', OLD."matrixUrgency", 'matrixImportance', OLD."matrixImportance", 'kanbanColumn', OLD."kanbanColumn", 'externalLinksJSON', OLD."externalLinksJSON", 'updatedAt', OLD."updatedAt", 'focusRank', OLD."focusRank", 'planningJSON', OLD."planningJSON"), NULL);
END;
CREATE TRIGGER change_log_task_conditions_insert AFTER INSERT ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'name', NEW."name", 'isLocation', NEW."isLocation", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_task_conditions_update AFTER UPDATE ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', NEW."id", 'update', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'name', OLD."name", 'isLocation', OLD."isLocation", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'workspaceId', NEW."workspaceId", 'name', NEW."name", 'isLocation', NEW."isLocation", 'isArchived', NEW."isArchived", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_task_conditions_delete AFTER DELETE ON task_conditions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'task_conditions', OLD."id", 'delete', json_object('id', OLD."id", 'workspaceId', OLD."workspaceId", 'name', OLD."name", 'isLocation', OLD."isLocation", 'isArchived', OLD."isArchived", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_dailies_insert AFTER INSERT ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'taskId', NEW."taskId", 'activeWeekdaysMask', NEW."activeWeekdaysMask", 'intervalDays', NEW."intervalDays", 'intervalAnchor', NEW."intervalAnchor", 'targetSeconds', NEW."targetSeconds", 'sortOrder', NEW."sortOrder", 'archivedAt', NEW."archivedAt", 'legacyDailyId', NEW."legacyDailyId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_dailies_update AFTER UPDATE ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', NEW."id", 'update', json_object('id', OLD."id", 'taskId', OLD."taskId", 'activeWeekdaysMask', OLD."activeWeekdaysMask", 'intervalDays', OLD."intervalDays", 'intervalAnchor', OLD."intervalAnchor", 'targetSeconds', OLD."targetSeconds", 'sortOrder', OLD."sortOrder", 'archivedAt', OLD."archivedAt", 'legacyDailyId', OLD."legacyDailyId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), json_object('id', NEW."id", 'taskId', NEW."taskId", 'activeWeekdaysMask', NEW."activeWeekdaysMask", 'intervalDays', NEW."intervalDays", 'intervalAnchor', NEW."intervalAnchor", 'targetSeconds', NEW."targetSeconds", 'sortOrder', NEW."sortOrder", 'archivedAt', NEW."archivedAt", 'legacyDailyId', NEW."legacyDailyId", 'createdAt', NEW."createdAt", 'updatedAt', NEW."updatedAt"));
END;
CREATE TRIGGER change_log_dailies_delete AFTER DELETE ON dailies WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'dailies', OLD."id", 'delete', json_object('id', OLD."id", 'taskId', OLD."taskId", 'activeWeekdaysMask', OLD."activeWeekdaysMask", 'intervalDays', OLD."intervalDays", 'intervalAnchor', OLD."intervalAnchor", 'targetSeconds', OLD."targetSeconds", 'sortOrder', OLD."sortOrder", 'archivedAt', OLD."archivedAt", 'legacyDailyId', OLD."legacyDailyId", 'createdAt', OLD."createdAt", 'updatedAt', OLD."updatedAt"), NULL);
END;
CREATE TRIGGER change_log_daily_contributions_insert AFTER INSERT ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'dailyId', NEW."dailyId", 'taskId', NEW."taskId", 'dayKey', NEW."dayKey", 'secondsLogged', NEW."secondsLogged", 'completedAt', NEW."completedAt", 'createdAt', NEW."createdAt"));
END;
CREATE TRIGGER change_log_daily_contributions_update AFTER UPDATE ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', NEW."id", 'update', json_object('id', OLD."id", 'dailyId', OLD."dailyId", 'taskId', OLD."taskId", 'dayKey', OLD."dayKey", 'secondsLogged', OLD."secondsLogged", 'completedAt', OLD."completedAt", 'createdAt', OLD."createdAt"), json_object('id', NEW."id", 'dailyId', NEW."dailyId", 'taskId', NEW."taskId", 'dayKey', NEW."dayKey", 'secondsLogged', NEW."secondsLogged", 'completedAt', NEW."completedAt", 'createdAt', NEW."createdAt"));
END;
CREATE TRIGGER change_log_daily_contributions_delete AFTER DELETE ON daily_contributions WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'daily_contributions', OLD."id", 'delete', json_object('id', OLD."id", 'dailyId', OLD."dailyId", 'taskId', OLD."taskId", 'dayKey', OLD."dayKey", 'secondsLogged', OLD."secondsLogged", 'completedAt', OLD."completedAt", 'createdAt', OLD."createdAt"), NULL);
END;
CREATE TRIGGER change_log_kanban_boards_insert AFTER INSERT ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', NEW."id", 'insert', NULL, json_object('id', NEW."id", 'columnsJSON', NEW."columnsJSON"));
END;
CREATE TRIGGER change_log_kanban_boards_update AFTER UPDATE ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', NEW."id", 'update', json_object('id', OLD."id", 'columnsJSON', OLD."columnsJSON"), json_object('id', NEW."id", 'columnsJSON', NEW."columnsJSON"));
END;
CREATE TRIGGER change_log_kanban_boards_delete AFTER DELETE ON kanban_boards WHEN (SELECT suppressed FROM undo_control WHERE id = 0) = 0
BEGIN
  INSERT INTO change_log(groupId, label, tableName, rowId, operation, beforeJSON, afterJSON) VALUES ((SELECT groupId FROM undo_control WHERE id = 0), (SELECT label FROM undo_control WHERE id = 0), 'kanban_boards', OLD."id", 'delete', json_object('id', OLD."id", 'columnsJSON', OLD."columnsJSON"), NULL);
END;

-- The migration ledger, so a fixture reads as migrated.
INSERT INTO grdb_migrations (identifier) VALUES ('v1_local_workspace');
INSERT INTO grdb_migrations (identifier) VALUES ('v2_metadata_and_focus');
INSERT INTO grdb_migrations (identifier) VALUES ('v3_dailies_as_contributions');
INSERT INTO grdb_migrations (identifier) VALUES ('v4_manual_focus_order');
INSERT INTO grdb_migrations (identifier) VALUES ('v5_task_source_identity');
INSERT INTO grdb_migrations (identifier) VALUES ('v6_inbox_as_a_system_list');
INSERT INTO grdb_migrations (identifier) VALUES ('v7_task_full_text_search');
INSERT INTO grdb_migrations (identifier) VALUES ('v8_undo_journal');
INSERT INTO grdb_migrations (identifier) VALUES ('v9_focus_block_start');
INSERT INTO grdb_migrations (identifier) VALUES ('v10_focus_points');
INSERT INTO grdb_migrations (identifier) VALUES ('v11_stable_visible_roots');
INSERT INTO grdb_migrations (identifier) VALUES ('v12_task_conditions_and_work');
INSERT INTO grdb_migrations (identifier) VALUES ('v13_legacy_visible_roots');
INSERT INTO grdb_migrations (identifier) VALUES ('v14_nested_lists');
INSERT INTO grdb_migrations (identifier) VALUES ('v15_kanban_board_history');
INSERT INTO grdb_migrations (identifier) VALUES ('v16_task_completion_time');
INSERT INTO undo_control (id, suppressed) VALUES (0, 1);
